name=input("What is your First name:- ")
mname=input("Your middle name:-")
lname=input("Your last Name:-")
subject=input("Add Your Subject here:- ")
to_whom=input("name of The Person You want To Send application:-")
reciever=input("Respected Principle,")
body=input("Body Of the Subject:-")
print("This Is Your Application")
print("To")
print("The Respected Principle,")
print(reciever)
print(to_whom)
print(reciever)
print("Subject:- ",subject)
print("Respected Principle,")
print(body)
print("Your's Faithfully,")
print("Name Of applicant:",lname+" "+name+" "+mname)